import 'package:flutter/material.dart';
import '../theme_colors.dart';

const nightColorLayer = ThemeColorLayer(
  sidebar: RoleColors(
    surface: Color(0xFF1E1E1E),
    foreground: Color(0xFFFFFFFF),
    foregroundActive: Color(0xFFFF9800),
    foregroundDisabled: Color(0xFFFFFFFF),
    backgroundFocused: Color(0xFFFF9800),
    backgroundActive: Color(0xFFFF9800),
    border: Color(0xFFFFFFFF),
    accent: Color(0xFFFF9800),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFFFFFFF),
  ),
  card: RoleColors(
    surface: Color(0xFF1E1E1E),
    foreground: Color(0xFFFFFFFF),
    foregroundActive: Color(0xFFFF9800),
    foregroundDisabled: Color(0x80FFFFFF),
    backgroundFocused: Color(0x1FFFF9800),
    backgroundActive: Color(0x2EFF9800),
    border: Color(0xFFFFFFFF),
    accent: Color(0xFFFF9800),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFFFFFFF),
  ),
  appBackground: RoleColors(
    surface: Color(0xFF000000),
    foreground: Color(0xFFFFFFFF),
    foregroundActive: Color(0xFFFF9800),
    foregroundDisabled: Color(0x80FFFFFF),
    backgroundFocused: Colors.transparent,
    backgroundActive: Colors.transparent,
    border: Color(0xFF333333),
    accent: Color(0xFFFF9800),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFFFFFFF),
  ),
  button: RoleColors(
    surface: Color(0xFF1E1E1E),
    foreground: Color(0xFFFFFFFF),
    foregroundActive: Color(0xFFFF9800),
    foregroundDisabled: Color(0x80FFFFFF),
    backgroundFocused: Color(0x1FFFF9800),
    backgroundActive: Color(0x2EFF9800),
    border: Color(0xFFFFFFFF),
    accent: Color(0xFFFF9800),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFFFFFFF),
  ),
);
